"""Per-app Git sync: init after Programmer, fixed commits per phase, optional push."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

from batch.flutter_ops import find_flutter_project

PHASE_COMMIT_MESSAGES: dict[str, str] = {
    "phase_pm_ui_plan": "docs(plan): pm ui and delivery plans",
    "phase_assets": "chore(assets): production artwork",
    "phase_pm": "docs(pm): feature blueprint",
    "phase_ui": "docs(ui): visual blueprint",
    "phase_programmer": "feat(dev): implement app",
    "phase_tester": "test(tester): main tool flow",
    # legacy keys (resume from old batches)
    "phase3": "chore(phase3): flutter scaffold",
    "phase4": "feat(phase4): implement app",
    "phase6": "chore(phase6): health check",
    "phase7": "test(phase7): widget tests",
}

GITIGNORE_TEMPLATE = "忽略文件模版.md"

CURSORIGNORE_HEADER = "# Auto-generated by batch git_ops — do not edit by hand.\n"
CURSORIGNORE_LINES: tuple[str, ...] = (
    "# 隔离批次内其他 app 容器：Cursor Agent 不应读取同批其他项目。",
    "../*-Flutter/",
    "../*-Swift/",
    "../*-OC/",
    "../_reports/",
)


def default_branch() -> str:
    return (os.environ.get("GIT_DEFAULT_BRANCH") or "master").strip() or "master"


def repo_root_from_workspace(workspace: Path) -> Path:
    """Git root is ``output/{App}-Swift|OC|Flutter/`` (parent of workspace)."""
    return workspace.parent


def _run_git(
    repo_root: Path,
    *args: str,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=check,
        capture_output=True,
        text=True,
    )


def _flutter_ready(workspace: Path) -> bool:
    fp = find_flutter_project(workspace)
    return fp is not None and (fp / "pubspec.yaml").is_file()


def _load_gitignore_template(static_dir: Path) -> str:
    path = static_dir / GITIGNORE_TEMPLATE
    if not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8").strip()
    if text.startswith("```"):
        text = re.sub(r"^```\w*\n?", "", text)
        text = re.sub(r"\n?```$", "", text)
    return text.strip()


def ensure_gitignore(repo_root: Path, static_dir: Path) -> None:
    dest = repo_root / ".gitignore"
    if dest.is_file():
        return
    body = _load_gitignore_template(static_dir)
    if body:
        dest.write_text(body + "\n", encoding="utf-8")


def ensure_cursorignore(repo_root: Path) -> Path:
    """Write ``.cursorignore`` at repo_root to hide sibling apps from Cursor.

    Idempotent: overwrites only when the auto-generated header is missing or the
    body differs, so user-added lines are preserved otherwise.
    """
    dest = repo_root / ".cursorignore"
    body = CURSORIGNORE_HEADER + "\n".join(CURSORIGNORE_LINES) + "\n"
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if existing.startswith(CURSORIGNORE_HEADER) and existing == body:
            return dest
        if not existing.startswith(CURSORIGNORE_HEADER):
            return dest
    repo_root.mkdir(parents=True, exist_ok=True)
    dest.write_text(body, encoding="utf-8")
    return dest


def ensure_git_repo(
    repo_root: Path,
    *,
    static_dir: Path,
    remote_url: str = "",
    branch: str | None = None,
) -> None:
    branch = branch or default_branch()
    remote_url = (remote_url or "").strip()
    git_dir = repo_root / ".git"

    if not git_dir.is_dir():
        _run_git(repo_root, "init", "-b", branch)
        ensure_gitignore(repo_root, static_dir)
        print(f"  >>> Git 已初始化: {repo_root} (branch={branch})")

    ensure_cursorignore(repo_root)

    if remote_url:
        _ensure_origin_remote(repo_root, remote_url)


def _ensure_origin_remote(repo_root: Path, remote_url: str) -> None:
    """Add or update ``origin`` when ``remote_url`` differs from task.csv / config."""
    probe = _run_git(repo_root, "remote", "get-url", "origin", check=False)
    if probe.returncode != 0:
        _run_git(repo_root, "remote", "add", "origin", remote_url)
        print(f"  >>> Git remote: origin → {remote_url}")
        return
    current = probe.stdout.strip()
    if current != remote_url:
        _run_git(repo_root, "remote", "set-url", "origin", remote_url)
        print(f"  >>> Git remote 已更新: {current} → {remote_url}")


def commit_if_dirty(repo_root: Path, message: str) -> bool:
    if not (repo_root / ".git").is_dir():
        return False
    _run_git(repo_root, "add", "-A")
    diff = _run_git(repo_root, "diff", "--cached", "--quiet", check=False)
    if diff.returncode == 0:
        return False
    _run_git(repo_root, "commit", "-m", message)
    print(f"  >>> Git commit: {message}")
    return True


def push_if_remote(
    repo_root: Path,
    remote_url: str = "",
    *,
    branch: str | None = None,
) -> bool:
    remote_url = (remote_url or "").strip()
    if not remote_url:
        return False
    if not (repo_root / ".git").is_dir():
        return False
    branch = branch or default_branch()
    _ensure_origin_remote(repo_root, remote_url)
    _run_git(repo_root, "push", "-u", "origin", branch)
    print(f"  >>> Git 已推送: origin/{branch}")
    return True


def sync_phase_git(
    workspace: Path,
    phase: str,
    static_dir: Path,
    *,
    remote_url: str = "",
    init: bool = False,
) -> bool:
    """Init (Phase 3) and/or commit with a fixed message when the phase succeeds."""
    message = PHASE_COMMIT_MESSAGES.get(phase)
    if not message:
        return False
    if not _flutter_ready(workspace):
        return False

    repo_root = repo_root_from_workspace(workspace)
    repo_root.mkdir(parents=True, exist_ok=True)

    if init or not (repo_root / ".git").is_dir():
        ensure_git_repo(
            repo_root,
            static_dir=static_dir,
            remote_url=remote_url,
        )

    return commit_if_dirty(repo_root, message)
