"""Per-app Git sync: init after Programmer, fixed commits per phase, optional push."""

from __future__ import annotations

import os
import json
import re
import subprocess
from pathlib import Path

from batch.flutter_ops import find_flutter_project

PHASE_COMMIT_MESSAGES: dict[str, str] = {
    "phase_pm_ui_plan": "docs(plan): pm ui and delivery plans",
    "phase_assets": "chore(assets): production artwork",
    "phase_pm": "docs(pm): feature blueprint",
    "phase_ui": "docs(ui): visual blueprint",
    "phase_programmer": "feat(dev): implement app",
    "phase_tester": "test(tester): main tool flow",
    # legacy keys (resume from old batches)
    "phase3": "chore(phase3): flutter scaffold",
    "phase4": "feat(phase4): implement app",
    "phase6": "chore(phase6): health check",
    "phase7": "test(phase7): widget tests",
}

GITIGNORE_TEMPLATE = "忽略文件模版.md"

CURSORIGNORE_HEADER = "# Auto-generated by batch git_ops — do not edit by hand.\n"
# Repo root is output/{App}-Swift|OC|Flutter/. Parent entries keep indexing
# inside this package tree (paths outside the app root are out of scope).
CURSORIGNORE_LINES: tuple[str, ...] = (
    "../*",
    "../../*",
)

WORKSPACE_CURSORIGNORE_HEADER = (
    "# Auto-generated by batch — do not edit by hand.\n"
)
# Agent --workspace is the app dir; hide everything above it from indexing.
WORKSPACE_CURSORIGNORE_LINES: tuple[str, ...] = (
    "../*",
    "../../*",
)


def default_branch() -> str:
    return (os.environ.get("GIT_DEFAULT_BRANCH") or "master").strip() or "master"


def repo_root_from_workspace(workspace: Path) -> Path:
    """Git root is ``output/{App}-Swift|OC|Flutter/`` (parent of workspace)."""
    return workspace.parent


def _run_git(
    repo_root: Path,
    *args: str,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=check,
        capture_output=True,
        text=True,
    )


def _flutter_ready(workspace: Path) -> bool:
    fp = find_flutter_project(workspace)
    return fp is not None and (fp / "pubspec.yaml").is_file()


def _is_h5_shell_workspace(workspace: Path) -> bool:
    ws = workspace.expanduser().resolve()
    reg = ws / "本包登记信息.json"
    if reg.is_file():
        try:
            data = json.loads(reg.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = {}
        if isinstance(data, dict):
            from batch.pack_type import is_h5_shell

            if is_h5_shell(str(data.get("packType") or "")):
                return True
    return (ws / "h5").is_dir() and (ws / "本包维度锁.json").is_file()


def _git_sync_ready(workspace: Path) -> bool:
    return _flutter_ready(workspace) or _is_h5_shell_workspace(workspace)


_GITIGNORE_PREVIEW_DROP = frozenset({"**/_preview/", "**/_preview/**"})
_GITIGNORE_WALLPAPER_NODE = "**/_preview/wallpaper/node_modules/"


def sync_gitignore_h5_rules(repo_root: Path, static_dir: Path) -> bool:
    """Ensure per-app .gitignore tracks ``_preview/`` but not wallpaper node_modules."""
    repo_root = repo_root.expanduser().resolve()
    dest = repo_root / ".gitignore"
    if not dest.is_file():
        body = _load_gitignore_template(static_dir)
        if body:
            dest.write_text(body + "\n", encoding="utf-8")
            return True
        return False
    lines = dest.read_text(encoding="utf-8").splitlines()
    changed = False
    kept: list[str] = []
    for line in lines:
        if line.strip() in _GITIGNORE_PREVIEW_DROP:
            changed = True
            continue
        kept.append(line)
    if _GITIGNORE_WALLPAPER_NODE not in [ln.strip() for ln in kept]:
        if kept and kept[-1].strip():
            kept.append("")
        kept.append(_GITIGNORE_WALLPAPER_NODE)
        changed = True
    if changed:
        dest.write_text("\n".join(kept).rstrip() + "\n", encoding="utf-8")
    return changed


def _load_gitignore_template(static_dir: Path) -> str:
    path = static_dir / GITIGNORE_TEMPLATE
    if not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8").strip()
    if text.startswith("```"):
        text = re.sub(r"^```\w*\n?", "", text)
        text = re.sub(r"\n?```$", "", text)
    return text.strip()


def ensure_gitignore(repo_root: Path, static_dir: Path) -> None:
    dest = repo_root / ".gitignore"
    if dest.is_file():
        sync_gitignore_h5_rules(repo_root, static_dir)
        return
    body = _load_gitignore_template(static_dir)
    if body:
        dest.write_text(body + "\n", encoding="utf-8")


def _write_managed_cursorignore(
    dest: Path,
    *,
    header: str,
    lines: tuple[str, ...],
) -> Path:
    """Write a managed ``.cursorignore``; skip overwrite of user-owned files."""
    body = header + "\n".join(lines) + "\n"
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        if existing.startswith(header) and existing == body:
            return dest
        if not existing.startswith(header):
            return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body, encoding="utf-8")
    return dest


def ensure_cursorignore(repo_root: Path) -> Path:
    """Write ``.cursorignore`` at package git root (``output/{App}-*``)."""
    return _write_managed_cursorignore(
        repo_root / ".cursorignore",
        header=CURSORIGNORE_HEADER,
        lines=CURSORIGNORE_LINES,
    )


def ensure_workspace_cursorignore(workspace: Path) -> Path:
    """Write ``.cursorignore`` at Agent ``--workspace`` (app directory)."""
    return _write_managed_cursorignore(
        workspace / ".cursorignore",
        header=WORKSPACE_CURSORIGNORE_HEADER,
        lines=WORKSPACE_CURSORIGNORE_LINES,
    )


def ensure_agent_path_isolation(workspace: Path) -> None:
    """Refresh path isolation files before a packaging Agent run."""
    ws = workspace.expanduser().resolve()
    ensure_workspace_cursorignore(ws)
    ensure_cursorignore(repo_root_from_workspace(ws))


def ensure_git_repo(
    repo_root: Path,
    *,
    static_dir: Path,
    remote_url: str = "",
    branch: str | None = None,
) -> None:
    branch = branch or default_branch()
    remote_url = (remote_url or "").strip()
    git_dir = repo_root / ".git"

    if not git_dir.is_dir():
        _run_git(repo_root, "init", "-b", branch)
        ensure_gitignore(repo_root, static_dir)
        print(f"  >>> Git 已初始化: {repo_root} (branch={branch})")

    ensure_cursorignore(repo_root)

    if remote_url:
        _ensure_origin_remote(repo_root, remote_url)


def _ensure_origin_remote(repo_root: Path, remote_url: str) -> None:
    """Add or update ``origin`` when ``remote_url`` differs from task.csv / config."""
    probe = _run_git(repo_root, "remote", "get-url", "origin", check=False)
    if probe.returncode != 0:
        _run_git(repo_root, "remote", "add", "origin", remote_url)
        print(f"  >>> Git remote: origin → {remote_url}")
        return
    current = probe.stdout.strip()
    if current != remote_url:
        _run_git(repo_root, "remote", "set-url", "origin", remote_url)
        print(f"  >>> Git remote 已更新: {current} → {remote_url}")


def commit_if_dirty(repo_root: Path, message: str) -> bool:
    if not (repo_root / ".git").is_dir():
        return False
    _run_git(repo_root, "add", "-A")
    diff = _run_git(repo_root, "diff", "--cached", "--quiet", check=False)
    if diff.returncode == 0:
        return False
    _run_git(repo_root, "commit", "-m", message)
    print(f"  >>> Git commit: {message}")
    return True


def push_if_remote(
    repo_root: Path,
    remote_url: str = "",
    *,
    branch: str | None = None,
) -> bool:
    remote_url = (remote_url or "").strip()
    if not remote_url:
        return False
    if not (repo_root / ".git").is_dir():
        return False
    branch = branch or default_branch()
    _ensure_origin_remote(repo_root, remote_url)
    _run_git(repo_root, "push", "-u", "origin", branch)
    print(f"  >>> Git 已推送: origin/{branch}")
    return True


def sync_phase_git(
    workspace: Path,
    phase: str,
    static_dir: Path,
    *,
    remote_url: str = "",
    init: bool = False,
) -> bool:
    """Init (Phase 3) and/or commit with a fixed message when the phase succeeds."""
    message = PHASE_COMMIT_MESSAGES.get(phase)
    if not message:
        return False
    if not _git_sync_ready(workspace):
        return False

    repo_root = repo_root_from_workspace(workspace)
    repo_root.mkdir(parents=True, exist_ok=True)
    sync_gitignore_h5_rules(repo_root, static_dir)

    if init or not (repo_root / ".git").is_dir():
        ensure_git_repo(
            repo_root,
            static_dir=static_dir,
            remote_url=remote_url,
        )

    return commit_if_dirty(repo_root, message)
