"""Sync h5_shell legal MD files into auto-generated vault JavaScript."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def _ensure_scripts_path() -> None:
    scripts_root = Path(__file__).resolve().parents[1]
    if str(scripts_root) not in sys.path:
        sys.path.insert(0, str(scripts_root))


_ensure_scripts_path()

from batch.h5_site_paths import site_entry_path, site_root_from_register, vault_dir_path
from batch.pack_type import is_h5_shell

REGISTER_FILE = "本包登记信息.json"

PRIVACY_MD_GLOB = "* Privacy Agreement.md"
TERMS_MD_GLOB = "* User Agreement.md"

PRIVACY_REQUIRED_HEADINGS = ("Children's Privacy",)
TERMS_REQUIRED_HEADINGS = ("Limitation of Liability",)

HEADING_RE = re.compile(r"^(#{1,3})\s+(.*)$")
BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
JS_STRING_RE = re.compile(
    r"(privacy|terms):\s*(\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*')",
    re.DOTALL,
)
INLINE_LEGAL_RE = re.compile(
    r"NS\.ui\.LEGAL\s*=\s*\{",
    re.IGNORECASE,
)


def _read_register(project: Path) -> dict:
    path = project / REGISTER_FILE
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except json.JSONDecodeError:
        return {}


def is_h5_shell_project(project: Path) -> bool:
    reg = _read_register(project)
    return is_h5_shell(str(reg.get("packType") or ""))


def find_privacy_md(project: Path) -> Path | None:
    matches = sorted(project.glob(PRIVACY_MD_GLOB))
    return matches[0] if matches else None


def find_terms_md(project: Path) -> Path | None:
    matches = sorted(project.glob(TERMS_MD_GLOB))
    return matches[0] if matches else None


def md_to_plain(text: str) -> str:
    """Convert legal MD (headings + paragraphs) to plain text for H5 display."""
    out: list[str] = []
    prev_blank = False
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            if not prev_blank and out:
                out.append("")
            prev_blank = True
            continue
        prev_blank = False
        heading = HEADING_RE.match(line)
        if heading:
            title = BOLD_RE.sub(r"\1", heading.group(2).strip())
            if out and out[-1] != "":
                out.append("")
            out.append(title)
            out.append("")
            continue
        out.append(BOLD_RE.sub(r"\1", line))
    while out and out[0] == "":
        out.pop(0)
    while out and out[-1] == "":
        out.pop()
    normalized: list[str] = []
    blank = False
    for line in out:
        if line == "":
            if not blank:
                normalized.append("")
            blank = True
        else:
            normalized.append(line)
            blank = False
    return "\n".join(normalized)


def normalize_for_compare(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").strip())


def resolve_prefix(project: Path) -> str:
    reg = _read_register(project)
    anti = reg.get("codeAntiCorrelation") or {}
    if isinstance(anti, dict):
        prefix = str(anti.get("dartCodePrefix") or "").strip()
        if prefix:
            return prefix
    from batch.workspace import dart_prefix

    return dart_prefix(project)


def resolve_global_ns(project: Path) -> str:
    prefix = resolve_prefix(project)
    return prefix[0].upper() + prefix[1:] if prefix else "App"


def bundled_script_rel(project: Path) -> Path:
    reg = _read_register(project)
    vault = site_root_from_register(reg).rstrip("/")
    prefix = resolve_prefix(project)
    return Path(vault) / f"{prefix}_panels" / f"{prefix}_legal_bundled.js"


def bundled_script_path(project: Path) -> Path:
    return project / bundled_script_rel(project)


def entry_htm_path(project: Path) -> Path:
    return site_entry_path(project)


def core_js_path(project: Path) -> Path:
    rel = bundled_script_rel(project)
    prefix = resolve_prefix(project)
    return project / rel.parent / f"{prefix}_core.js"


def render_bundled_js(
    *,
    privacy_text: str,
    terms_text: str,
    privacy_src: str,
    terms_src: str,
    global_ns: str,
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    privacy_json = json.dumps(privacy_text, ensure_ascii=False)
    terms_json = json.dumps(terms_text, ensure_ascii=False)
    return (
        "/* AUTO-GENERATED by sync_h5_legal_bundled.py — DO NOT EDIT */\n"
        f"/* generatedAt: {generated_at} */\n"
        f"/* privacySource: {privacy_src} */\n"
        f"/* termsSource: {terms_src} */\n"
        "(function (global) {\n"
        "  'use strict';\n"
        f"  var NS = global.{global_ns} = global.{global_ns} || {{}};\n"
        "  NS.ui = NS.ui || {};\n"
        "  NS.ui.LEGAL = {\n"
        f"    privacy: {privacy_json},\n"
        f"    terms: {terms_json}\n"
        "  };\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def extract_legal_from_js(js_text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for key in ("privacy", "terms"):
        match = re.search(rf"{key}:\s*(\"(?:\\.|[^\"\\])*\"|'(?:\\.|[^'\\])*')", js_text)
        if not match:
            continue
        out[key] = json.loads(match.group(1))
    return out


def load_expected_legal(project: Path) -> tuple[dict[str, str], dict[str, str]]:
    privacy_md = find_privacy_md(project)
    terms_md = find_terms_md(project)
    if privacy_md is None or terms_md is None:
        missing = []
        if privacy_md is None:
            missing.append(PRIVACY_MD_GLOB)
        if terms_md is None:
            missing.append(TERMS_MD_GLOB)
        raise FileNotFoundError(f"Missing legal MD: {', '.join(missing)}")
    privacy_text = md_to_plain(privacy_md.read_text(encoding="utf-8"))
    terms_text = md_to_plain(terms_md.read_text(encoding="utf-8"))
    meta = {
        "privacy": privacy_md.name,
        "terms": terms_md.name,
    }
    return {"privacy": privacy_text, "terms": terms_text}, meta


def sync_h5_legal_bundled(project: Path, *, write: bool = True) -> Path:
    project = project.expanduser().resolve()
    if not is_h5_shell_project(project):
        raise ValueError(f"Not an h5_shell project: {project}")

    expected, meta = load_expected_legal(project)
    out_path = bundled_script_path(project)
    content = render_bundled_js(
        privacy_text=expected["privacy"],
        terms_text=expected["terms"],
        privacy_src=meta["privacy"],
        terms_src=meta["terms"],
        global_ns=resolve_global_ns(project),
    )
    if write:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
    return out_path


def verify_h5_legal_bundled(project: Path) -> list[str]:
    """Return issue strings; empty means OK."""
    project = project.expanduser().resolve()
    issues: list[str] = []

    if not is_h5_shell_project(project):
        return issues

    try:
        expected, _meta = load_expected_legal(project)
    except FileNotFoundError as exc:
        issues.append(str(exc))
        return issues

    bundled = bundled_script_path(project)
    if not bundled.is_file():
        issues.append(f"MISSING: {bundled.relative_to(project)}")
        return issues

    actual = extract_legal_from_js(bundled.read_text(encoding="utf-8"))
    for key in ("privacy", "terms"):
        if key not in actual:
            issues.append(f"BUNDLED: missing {key} string in {bundled.name}")
            continue
        if normalize_for_compare(actual[key]) != normalize_for_compare(expected[key]):
            ratio = len(actual[key]) / max(len(expected[key]), 1)
            issues.append(
                f"MISMATCH: {key} bundled text differs from MD "
                f"(len {len(actual[key])} vs {len(expected[key])}, ratio {ratio:.2f})"
            )
        min_len = 0.85 * len(expected[key])
        if len(actual[key]) < min_len:
            issues.append(
                f"SHORT: {key} bundled text too short "
                f"({len(actual[key])} < {min_len:.0f})"
            )

    for heading in PRIVACY_REQUIRED_HEADINGS:
        if heading not in expected["privacy"]:
            issues.append(f"MD: privacy missing required heading {heading!r}")
        elif heading not in actual.get("privacy", ""):
            issues.append(f"BUNDLED: privacy missing required section {heading!r}")

    for heading in TERMS_REQUIRED_HEADINGS:
        if heading not in expected["terms"]:
            issues.append(f"MD: terms missing required heading {heading!r}")
        elif heading not in actual.get("terms", ""):
            issues.append(f"BUNDLED: terms missing required section {heading!r}")

    entry = entry_htm_path(project)
    if entry.is_file():
        rel_script = bundled_script_rel(project).as_posix()
        panels_rel = rel_script.split("/")[-2] + "/" + bundled_script_path(project).name
        entry_text = entry.read_text(encoding="utf-8", errors="ignore")
        if bundled.name not in entry_text:
            issues.append(
                f"ENTRY: {entry.name} must load {bundled.name} before core.js"
            )
        elif panels_rel not in entry_text and rel_script not in entry_text:
            issues.append(f"ENTRY: script path for {bundled.name} not referenced")
    else:
        issues.append(f"MISSING: entry htm at {entry.name if entry else 'bundleEntryPath'}")

    core = core_js_path(project)
    if core.is_file():
        core_text = core.read_text(encoding="utf-8", errors="ignore")
        if INLINE_LEGAL_RE.search(core_text):
            issues.append(
                f"CORE: remove inline NS.ui.LEGAL from {core.relative_to(project)} "
                "(use generated legal_bundled.js only)"
            )

    return issues


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_dir", type=Path, help="Flutter project directory")
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Verify bundled JS matches MD without writing",
    )
    args = parser.parse_args(argv)

    project = args.project_dir.expanduser().resolve()
    if not project.is_dir():
        print(f"ERROR: not a directory: {project}", file=sys.stderr)
        return 2

    if not is_h5_shell_project(project):
        print(f"SKIP: not h5_shell ({project.name})")
        return 0

    if args.check_only:
        issues = verify_h5_legal_bundled(project)
        if issues:
            print(f"project: {project.name}")
            for item in issues:
                print(f"  ISSUE: {item}")
            return 1
        print(f"OK: h5 legal bundled matches MD ({project.name})")
        return 0

    try:
        out_path = sync_h5_legal_bundled(project, write=True)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    issues = verify_h5_legal_bundled(project)
    print(f"Wrote: {out_path.relative_to(project)}")
    if issues:
        print("WARN post-sync:")
        for item in issues:
            print(f"  {item}")
        return 1
    print("OK: synced and verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
